services:
  db:
    image: postgres:15
    container_name: findme_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /backend
    container_name: findme_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - APP_ENV=${APP_ENV}
      - DATABASE_URL=${DATABASE_URL}
      
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: findme_frontend
    ports:
    - "5173:5173"
    working_dir: /frontend

  nginx:
    build:
      context: ./nginx
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl.conf:/etc/nginx/conf.d/ssl.conf
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/logs:/var/log/nginx

volumes:
  db_data:
