"""create initial tables

Revision ID: 7aad23e69781
Revises: 
Create Date: 2025-06-19 06:27:24.631470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7aad23e69781'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('M_CATEGORIES',
    sa.Column('MCTG_CODE', sa.Integer(), nullable=False),
    sa.Column('MCTG_NAME', sa.String(length=20), nullable=False),
    sa.Column('MCTG_CREATED_AT', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('MCTG_UPDATED_AT', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('MCTG_CODE')
    )
    op.create_table('M_LOCATIONS',
    sa.Column('MLCT_CODE', sa.Integer(), nullable=False),
    sa.Column('MLCT_NAME', sa.String(length=20), nullable=False),
    sa.Column('MLCT_CREATED_AT', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('MLCT_UPDATED_AT', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('MLCT_CODE')
    )
    op.create_table('M_STAFFS',
    sa.Column('MSTF_CODE', sa.Integer(), nullable=False),
    sa.Column('MSTF_NAME', sa.String(length=30), nullable=False),
    sa.Column('MSTF_CREATED_AT', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('MSTF_UPDATED_AT', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('MSTF_CODE')
    )
    op.create_table('M_STORAGES',
    sa.Column('MSTR_CODE', sa.Integer(), nullable=False),
    sa.Column('MSTR_NAME', sa.String(length=20), nullable=False),
    sa.Column('MSTR_CREATED_AT', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('MSTR_UPDATED_AT', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('MSTR_CODE')
    )
    op.create_table('M_SYSTEM',
    sa.Column('MSYS_ID', sa.Integer(), nullable=False),
    sa.Column('MSYS_IMGCOUNT', sa.SmallInteger(), nullable=True),
    sa.Column('MSYS_CREATED_AT', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('MSYS_UPDATED_AT', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('MSYS_ID')
    )
    op.create_table('D_ITEMS',
    sa.Column('DITM_ID', sa.Integer(), nullable=False),
    sa.Column('DITM_NAME', sa.String(length=30), nullable=False),
    sa.Column('DITM_CATEGORY_CODE', sa.Integer(), nullable=False),
    sa.Column('DITM_FOUND_AT', sa.Integer(), nullable=False),
    sa.Column('DITM_FOUND_AT_NOTE', sa.Text(), nullable=True),
    sa.Column('DITM_FOUND_DATE', sa.Date(), nullable=False),
    sa.Column('DITM_STORAGE_CODE', sa.Integer(), nullable=False),
    sa.Column('DITM_STAFF_CODE', sa.Integer(), nullable=False),
    sa.Column('DITM_IS_RETURNED', sa.SmallInteger(), nullable=False),
    sa.Column('DITM_RETURN_DATE', sa.Date(), nullable=True),
    sa.Column('DITM_RETURNED_BY', sa.Integer(), nullable=True),
    sa.Column('DITM_MEMO', sa.Text(), nullable=True),
    sa.Column('DITM_CREATED_AT', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('DITM_UPDATED_AT', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['DITM_CATEGORY_CODE'], ['M_CATEGORIES.MCTG_CODE'], ),
    sa.ForeignKeyConstraint(['DITM_FOUND_AT'], ['M_LOCATIONS.MLCT_CODE'], ),
    sa.ForeignKeyConstraint(['DITM_RETURNED_BY'], ['M_STAFFS.MSTF_CODE'], ),
    sa.ForeignKeyConstraint(['DITM_STAFF_CODE'], ['M_STAFFS.MSTF_CODE'], ),
    sa.ForeignKeyConstraint(['DITM_STORAGE_CODE'], ['M_STORAGES.MSTR_CODE'], ),
    sa.PrimaryKeyConstraint('DITM_ID')
    )
    op.create_table('D_ITEM_IMAGES',
    sa.Column('DIMG_ITEM_ID', sa.Integer(), nullable=False),
    sa.Column('DIMG_SEQ', sa.SmallInteger(), nullable=False),
    sa.Column('DIMG_PATH', sa.Text(), nullable=False),
    sa.Column('DIMG_CREATED_AT', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('DIMG_UPDATED_AT', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['DIMG_ITEM_ID'], ['D_ITEMS.DITM_ID'], ),
    sa.PrimaryKeyConstraint('DIMG_ITEM_ID', 'DIMG_SEQ')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('D_ITEM_IMAGES')
    op.drop_table('D_ITEMS')
    op.drop_table('M_SYSTEM')
    op.drop_table('M_STORAGES')
    op.drop_table('M_STAFFS')
    op.drop_table('M_LOCATIONS')
    op.drop_table('M_CATEGORIES')
    # ### end Alembic commands ###
