"""initial lowercase schema

Revision ID: 9db367b38bc4
Revises: 
Create Date: 2025-07-14 01:31:07.440085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9db367b38bc4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('m_categories',
    sa.Column('mctg_code', sa.Integer(), nullable=False),
    sa.Column('mctg_name', sa.String(length=20), nullable=False),
    sa.Column('mctg_order', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('mctg_valid', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('mctg_created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('mctg_updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('mctg_code')
    )
    op.create_table('m_locations',
    sa.Column('mlct_code', sa.Integer(), nullable=False),
    sa.Column('mlct_name', sa.String(length=20), nullable=False),
    sa.Column('mlct_created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('mlct_updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('mlct_code')
    )
    op.create_table('m_staffs',
    sa.Column('mstf_code', sa.Integer(), nullable=False),
    sa.Column('mstf_name', sa.String(length=30), nullable=False),
    sa.Column('mstf_created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('mstf_updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('mstf_code')
    )
    op.create_table('m_storages',
    sa.Column('mstr_code', sa.Integer(), nullable=False),
    sa.Column('mstr_name', sa.String(length=20), nullable=False),
    sa.Column('mstr_created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('mstr_updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('mstr_code')
    )
    op.create_table('m_system',
    sa.Column('msys_id', sa.Integer(), nullable=False),
    sa.Column('msys_imgcount', sa.SmallInteger(), nullable=True),
    sa.Column('msys_created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('msys_updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('msys_id')
    )
    op.create_table('d_items',
    sa.Column('ditm_id', sa.Integer(), nullable=False),
    sa.Column('ditm_name', sa.String(length=30), nullable=False),
    sa.Column('ditm_category_code', sa.Integer(), nullable=False),
    sa.Column('ditm_found_at', sa.Integer(), nullable=False),
    sa.Column('ditm_found_at_note', sa.Text(), nullable=True),
    sa.Column('ditm_found_date', sa.Date(), nullable=False),
    sa.Column('ditm_storage_code', sa.Integer(), nullable=False),
    sa.Column('ditm_staff_code', sa.Integer(), nullable=False),
    sa.Column('ditm_isreturned', sa.SmallInteger(), nullable=False),
    sa.Column('ditm_return_date', sa.Date(), nullable=True),
    sa.Column('ditm_returned_by', sa.Integer(), nullable=True),
    sa.Column('ditm_memo', sa.Text(), nullable=True),
    sa.Column('ditm_created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ditm_updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ditm_category_code'], ['m_categories.mctg_code'], ),
    sa.ForeignKeyConstraint(['ditm_found_at'], ['m_locations.mlct_code'], ),
    sa.ForeignKeyConstraint(['ditm_returned_by'], ['m_staffs.mstf_code'], ),
    sa.ForeignKeyConstraint(['ditm_staff_code'], ['m_staffs.mstf_code'], ),
    sa.ForeignKeyConstraint(['ditm_storage_code'], ['m_storages.mstr_code'], ),
    sa.PrimaryKeyConstraint('ditm_id')
    )
    op.create_table('d_item_images',
    sa.Column('dimg_item_id', sa.Integer(), nullable=False),
    sa.Column('dimg_seq', sa.SmallInteger(), nullable=False),
    sa.Column('dimg_path', sa.Text(), nullable=False),
    sa.Column('dimg_created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('dimg_updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dimg_item_id'], ['d_items.ditm_id'], ),
    sa.PrimaryKeyConstraint('dimg_item_id', 'dimg_seq')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('d_item_images')
    op.drop_table('d_items')
    op.drop_table('m_system')
    op.drop_table('m_storages')
    op.drop_table('m_staffs')
    op.drop_table('m_locations')
    op.drop_table('m_categories')
    # ### end Alembic commands ###
